# Generated by Django 4.2.3 on 2023-07-31 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=500)),
                ('discount_percent', models.IntegerField(default=0, max_length=3)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0, max_length=10)),
                ('amount', models.IntegerField(default=0, max_length=10)),
                ('provider', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('provider', models.CharField(default='', max_length=100)),
                ('account_number', models.IntegerField(default=0, max_length=20)),
                ('expiry_date', models.DateField(default=datetime.datetime(2023, 8, 1, 0, 15, 2, 673799))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(default='', max_length=100)),
                ('address_line_2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('postal_code', models.IntegerField(default=0, max_length=7)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0, max_length=12)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0, max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('sku', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0, max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.productcategory')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.discount')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.productinventory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.orderdetails')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.paymentdetails'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, max_length=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.product')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.shoppingsession')),
            ],
        ),
    ]
